twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
    globals:
        issue_number: "%issue_number%"
        issue_url: "%issue_url%"
        reproducer_url: "%reproducer_url%"

when@test:
    twig:
        strict_variables: true
