twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
    globals:
        issue_number: "%issue_number%"

when@test:
    twig:
        strict_variables: true
